name: Build Docker Image

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t cuda-ubuntu .
      - name: Deploy
        run: |
          TAG="ghcr.io/$GITHUB_ACTOR/cuda-ubuntu"
          VERSION="$(date "+%Y%m%d")"
          docker tag cuda-ubuntu $TAG:$VERSION
          docker tag cuda-ubuntu $TAG:latest
          docker images $TAG
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push $TAG:$VERSION
          docker push $TAG:latest
